services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - ./.env.db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U dev_root -d dev"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB

  app:
    build: ./app
    container_name: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./app/.env
      - ./.env.db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512MB